class ProcedureModel {
  id: string;
  url_key: string;
  title: string;
  category_id: string;
  created_by: string;
  created_at: string;
  status: string;
  files: string;
  total_views: string;
  number: string;
  image_url: string;
  user_id: string;
  result: string;
  profile_composition: string;
  the_order_execution: string;
  conditions_required: string;
  form: string;
  settlement_term: string;
  postal_services: string;
  price: string;
  content: string;
  image: string;
  procedures_before: string;
  procedures_same_time: string;
  procedures_after: string;
  procedures_related: string;
  procedures_viewed: string;
  actual_implementation: string;
  deleted: string;
  crawl_id: string;
  crawl_link: string;
  area_id: string;
  object_implementation: string;
  legal_grounds: string;
  profile_composition_files: string;
  updated_at: string;
  co_quan_co_tham_quyen: string;
  so_quyet_dinh: string;
  cap_thuc_hien: string;
  loai_thu_tuc: string;
  co_quan_thuc_hien: string;
  co_quan_duoc_uy_quyen: string;
  version: string;
  co_quan_phoi_hop: string;
  tu_khoa: string;
  description: string;
  organization_id: string;
  organization_tinh_id: string;
  dia_chi_tiep_nhan_hs: string;
  approved: string;
  file_id: string;
  service_type: string;
  organization_name: string;
  area_name: string;

  constructor(args: any) {
    this.id = args.id ?? '';
    this.url_key = args.url_key ?? '';
    this.title = args.title ?? '';
    this.category_id = args.category_id ?? '';
    this.created_by = args.created_by ?? '';
    this.created_at = args.created_at ?? '';
    this.status = args.status ?? '';
    this.files = args.files ?? '';
    this.total_views = args.total_views ?? '';
    this.number = args.number ?? '';
    this.image_url = args.image_url ?? '';
    this.user_id = args.user_id ?? '';
    this.result = args.result ?? '';
    this.profile_composition = args.profile_composition ?? '';
    this.the_order_execution = args.the_order_execution ?? '';
    this.conditions_required = args.conditions_required ?? '';
    this.form = args.form ?? '';
    this.settlement_term = args.settlement_term ?? '';
    this.postal_services = args.postal_services ?? '';
    this.price = args.price ?? '';
    this.content = args.content ?? '';
    this.image = args.image ?? '';
    this.procedures_before = args.procedures_before ?? '';
    this.procedures_same_time = args.procedures_same_time ?? '';
    this.procedures_after = args.procedures_after ?? '';
    this.procedures_related = args.procedures_related ?? '';
    this.procedures_viewed = args.procedures_viewed ?? '';
    this.actual_implementation = args.actual_implementation ?? '';
    this.deleted = args.deleted ?? '';
    this.crawl_id = args.crawl_id ?? '';
    this.crawl_link = args.crawl_link ?? '';
    this.area_id = args.area_id ?? '';
    this.object_implementation = args.object_implementation ?? '';
    this.legal_grounds = args.legal_grounds ?? '';
    this.profile_composition_files = args.profile_composition_files ?? '';
    this.updated_at = args.updated_at ?? '';
    this.co_quan_co_tham_quyen = args.co_quan_co_tham_quyen ?? '';
    this.so_quyet_dinh = args.so_quyet_dinh ?? '';
    this.cap_thuc_hien = args.cap_thuc_hien ?? '';
    this.loai_thu_tuc = args.loai_thu_tuc ?? '';
    this.co_quan_thuc_hien = args.co_quan_thuc_hien ?? '';
    this.co_quan_duoc_uy_quyen = args.co_quan_duoc_uy_quyen ?? '';
    this.version = args.version ?? '';
    this.co_quan_phoi_hop = args.co_quan_phoi_hop ?? '';
    this.tu_khoa = args.tu_khoa ?? '';
    this.description = args.description ?? '';
    this.organization_id = args.organization_id ?? '';
    this.organization_tinh_id = args.organization_tinh_id ?? '';
    this.dia_chi_tiep_nhan_hs = args.dia_chi_tiep_nhan_hs ?? '';
    this.approved = args.approved ?? '';
    this.file_id = args.file_id ?? '';
    this.service_type = args.service_type ?? '';
    this.organization_name = args.organization_name ?? '';
    this.area_name = args.area_name ?? '';
  }
}

export default ProcedureModel;
